### ISSUE TITLE
[Docs] add request body examples

### ISSUE THREAD

**Issue by kevinccbsg** [BRIKEV/express-jsdoc-swagger#26]
We have to complete documentation of [request body](https://swagger.io/docs/specification/describing-request-body/) examples.

We have to save them as the other ones described in this [README file](https://github.com/BRIKEV/express-jsdoc-swagger/blob/master/examples/README.md)

You can follow the [integration tests](https://github.com/BRIKEV/express-jsdoc-swagger/blob/master/test/transforms/paths/requestBody.test.js) of this feature to create the documentation.

## Tasks

- [x] Update [README file](https://github.com/BRIKEV/express-jsdoc-swagger/blob/master/examples/README.md)
- [x] Add basic example
- [ ] Add example with components
- [ ] Add example with multiple endpoints
- [ ] Add full example
